---
- name: Install prometheus
  apt:
    name: prometheus
    state: latest

- name: Start Prometheus
  systemd:
    name: prometheus
    state: started
    enabled: yes

- name: Create path
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
  loop:
    - /etc/prometheus
    - /var/lib/prometheus
    - /var/log/prometheus

- name: Create empty file
  file:
    path: "/var/log/prometheus/prometheus.log"
    state: touch
    owner: "prometheus"
    group: "prometheus"
    mode: '0644'

- name: Dest file
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml

- name: Reload Prometheus
  systemd:
    name: prometheus
    state: restarted
    enabled: yes
    daemon_reload: yes
