---
- name: Create prometheus serviceAccount
  user:
    name: prometheus
    shell: /bin/false
    system: yes

- name: Download and unpack Prometheus
  unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v2.52.0/prometheus-2.52.0.linux-amd64.tar.gz
    dest: /opt
    remote_src: yes
    owner: prometheus
    group: prometheus

- name: Copy systemd
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
  notify: Start Prometheus

- name: Create path
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
  loop:
    - /etc/prometheus
    - /var/lib/prometheus
    - /var/log/prometheus

- name: Create empty file
  file:
    path: "/var/log/prometheus/prometheus.log" 
    state: touch
    owner: "prometheus"  
    group: "prometheus" 
    mode: '0644'

- name: Dest file
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
  notify: Reload Prometheus