- name: Download elasticsearch
  apt:
      deb: "https://mirror.yandex.ru/mirrors/elastic/7/pool/main/e/elasticsearch/elasticsearch-7.15.0-amd64.deb"
      state: present

- name: Install elasticsearch
  systemd:
    name: elasticsearch
    enabled: yes
    state: started
    daemon_reload: true

- name: Copy elasticsearch configuration file
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml

- name: restart elasticsearch
  systemd:
    name: elasticsearch
    state: restarted