---
- name: Install nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: Start nginx
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: yes

- name: Create index.html
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.nginx-debian.html
  notify:
    - Reload nginx