---
all:
  hosts:
    nexus-01:
      ansible_host: 158.160.31.117
  children:
    nexus:
      hosts:
        nexus-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: dasha21a
    ansible_ssh_private_key_file: /Users/daracvetkova/.ssh/id_rsa