apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cfg
  labels:
    app: nginx-nginx
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Welcome to nginx!</title>
    </head>
    <body>
    <h1>Мое домашнее задание в Нетологии</h1>
    </body>
    </html>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: multitool-cfg
  labels:
    app:  multitool-cfg
data:
  HTTP_PORT: "8080"
  HTTPS_PORT: "8443"