apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset-name
  labels:
    app: multitool
spec:
  selector:
    matchLabels:
      name: daemonset-name
  template:
    metadata:
      labels:
        name: daemonset-name
    spec:
      containers:
        - name: multitool
          image: wbitt/network-multitool
          volumeMounts:
            - name: logdir
              mountPath: /node-log/syslog
            - name: varlog
              mountPath: /var/log/syslog
              readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
        - name: logdir
          hostPath:
            path: /var/log
        - name: varlog
          hostPath:
            path: /var/log