- name: Install grafana
  apt:
    name: grafana
    state: latest

- name: Start Grafana
  systemd:
    name: grafana-server
    enabled: yes
    state: started

- name: Copy datasource config
  template:
    src: prometheus.yml.j2
    dest: /etc/grafana/provisioning/datasources/prometheus.yml

- name: Copy datasource config
  template:
    src: dashboards.yml.j2
    dest: /etc/grafana/provisioning/dashboards/dashboards.yaml

- name: restart grafana
  systemd:
    name: grafana-server
    state: restarted