- name: Download Grafana
  get_url:
    url: "https://dl.grafana.com/oss/release/grafana_11.0.0_amd64.deb"
    dest: "/tmp/grafana_11.0.0_amd64.deb"

- name: Install Grafana
  apt:
    deb: "/tmp/grafana_9.2.4_amd64.deb"
    state: present

- name: Start Grafana
  systemd:
    name: grafana
    enabled: yes
    state: started

- name: Copy datasource config
  template:
    src: prometheus.yml.j2
    dest: /etc/grafana/provisioning/datasources/prometheus.yml

- name: Copy dashboard node exporter
  template:
    src: node_exporter_dashboard.json
    dest: /etc/grafana/provisioning/dashboards/node_exporter_dashboard.json

- name: Copy datasource config
  template:
    src: dashboards.yml.j2
    dest: /etc/grafana/provisioning/dashboards/dashboards.yaml
  notify:
    - restart grafana