---
- name: Enable TCP forwarding on the bastion host
  hosts: bastion
  become: yes
  tasks:
    - name: Uncomment the 'AllowTcpForwarding yes' line in sshd_config
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^s*#?s*AllowTcpForwardings+no'
        line: 'AllowTcpForwarding yes'
        backrefs: yes
        state: present

    - name: Restart SSH service to apply changes
      ansible.builtin.service:
        name: sshd
        state: restarted
    - name: Enable packet forwarding for IPv4
      ansible.builtin.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: yes
    - name: Set up NAT using iptables
      ansible.builtin.iptables:
        table: nat
        chain: POSTROUTING
        jump: MASQUERADE
        out_interface: "eth0"
        state: present

    - name: Копирование id_rsa чтобы можно было находясь на bastion-host легко ходить на все остальные ВМ
      copy:
        src: /Users/daracvetkova/.ssh/id_rsa
        dest: /home/dasha21a/.ssh/id_rsa
        owner: dasha21a
        group: dasha21a
        mode: 0600
#nginx
- name: Deploy Nginx
  hosts: webservers
  become: yes
  roles:
    - nginx

#prometheus
- name: Deploy Prometheus
  hosts: prometheus
  become: yes
  roles:
    - prometheus

#node-exporter
- name: Deploy Node-exporter
  hosts: all
  become: yes
  roles:
    - node_exporter

#grafana
- name: Deploy Grafana
  hosts: grafana
  become: yes
  roles:
    - grafana

#elasticsearch
- name: Deploy Elasticsearch
  hosts: elasticsearch
  become: yes
  roles:
    - elasticsearch

#kibana
- name: Deploy Kibana
  hosts: kibana
  become: yes
  roles:
    - kibana

#filebeat
- name: Deploy Filebeat
  hosts: filebeat
  become: yes
  roles:
    - filebeat