---
- name: Install Python
  hosts: all
  become: yes
  tasks:
    - name: Install python3
      ansible.builtin.yum:
        name:
          - python3
        state: present
- name: Install Clickhouse
  hosts: clickhouse
  become: yes
  handlers:
    - name: Start clickhouse service
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - name: Mess with clickhouse distrib
      block:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ clickhouse_version }}.x86_64.rpm"
            dest: "./{{ item }}-{{ clickhouse_version }}.rpm"
            mode: "0644"
          with_items: "{{ clickhouse_packages }}"
      rescue:
        - name: Get clickhouse distrib (rescue)
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/clickhouse-common-static-{{ clickhouse_version }}.x86_64.rpm"
            dest: "./clickhouse-common-static-{{ clickhouse_version }}.rpm"
            mode: "0644"
    - name: Install clickhouse packages
      ansible.builtin.yum:
        name:
          - clickhouse-common-static-{{ clickhouse_version }}.rpm
          - clickhouse-client-{{ clickhouse_version }}.rpm
          - clickhouse-server-{{ clickhouse_version }}.rpm
      notify: Start clickhouse service
    - name: Flush handlers
      meta: flush_handlers
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0
    - name: Install required packages
      ansible.builtin.yum:
        name:
          - unzip
          - curl
        state: present
- name: Install and configure Vector
  hosts: vector
  become: yes
  handlers:
    - name: Reload vector service
      ansible.builtin.systemd:
        name: vector
        state: restarted
  tasks:
    - name: Download Vector distribution
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/{{vector_version}}/vector-{{ vector_version }}-1.x86_64.rpm"
        dest: "./vector-{{ vector_version }}.rpm"
    - name: Install Vector
      ansible.builtin.yum:
        name: "./vector-{{ vector_version }}.rpm"
        state: present
    - name: Deploy Vector configuration
      ansible.builtin.template:
        src: vector.j2
        dest: "/etc/vector/vector.toml"
        mode: '0644'
      notify: Reload vector service
- name: Install and configure LightHouse
  hosts: lighthouse
  become: yes
  handlers:
    - name: Restart nginx service
      ansible.builtin.systemd:
        name: nginx
        state: restarted
  tasks:
    - name: Install required packages
      ansible.builtin.yum:
        name: git
        state: present
    - name: Clone LightHouse repository
      ansible.builtin.git:
        repo: 'https://github.com/VKCOM/lighthouse.git'
        dest: '/var/www/lighthouse'
        version: master
    - name: Ensure permissions on LightHouse directory
      ansible.builtin.file:
        path: '/var/www/lighthouse'
        state: directory
        mode: '0755'
    - name: Install EPEL repo
      ansible.builtin.yum:
        name: epel-release
        state: present
    - name: Install Nginx
      ansible.builtin.yum:
        name: nginx
        state: present
    - name: Deploy Nginx configuration for LightHouse
      ansible.builtin.template:
        src: nginx_lighthouse.j2
        dest: "/etc/nginx/conf.d/lighthouse.conf"
        mode: '0644'
      notify: Restart nginx service
    - name: Ensure Nginx is running
      ansible.builtin.systemd:
        name: nginx
        state: started